### ISSUE TITLE
Checklist for Elm 0.18

### ISSUE THREAD

**Issue by klazuka** [durkiewicz/elm-plugin#41]
Unlike Elm 0.17, version 0.18 will not require an immediate plugin update as it doesn't break the overall syntactic structure, but there are a few things that would be nice to do:

- [ ] remove backtick syntax
- [ ] disallow primes in identifiers
- [ ] remove [..] List range syntax (was it ever supported by the plugin?)
- [ ] [proposed changes](https://groups.google.com/d/msg/elm-dev/mMUCvhPEJxQ/rgW9v_2WAgAJ) to the set of default imports

**Comment by bgourlie** [comment]
Any chance https://github.com/durkiewicz/elm-plugin/issues/40 could be added to the checklist?

**Comment by klazuka** [comment]
Well, it doesn't have anything to do with 0.18, but presumably it would be easy to fix while making other changes to the lexer.

**Comment by durkiewicz** [comment]
@klazuka Are those things committed to the `elm-compiler` repo? Or they are just discussed?

I find those things a bit controversial (not as controversial as removing signals in 0.17, but still). I wish those guys focus on compiler's performance instead of inventing such things...

**Comment by klazuka** [comment]
I don't know if the changes to default imports have been commited, but the backticks and the 'prime' notation are definitely in the 0.18 beta build. The place to find this stuff is on the elm-dev google group.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
